CREATE TABLE IF NOT EXISTS tb_home_care_avaliacao (
    id_home_care INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fk_internacao_hc INT NOT NULL,
    fk_usuario_hc INT NULL,
    data_atualizacao_hc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_hc VARCHAR(50) NULL,
    fornecedor_hc VARCHAR(120) NULL,
    modalidade_sugerida_hc VARCHAR(60) NULL,
    modalidade_aprovada_hc VARCHAR(60) NULL,
    previsao_implantacao_hc DATE NULL,
    data_visita_domiciliar_hc DATE NULL,
    barreira_principal_hc VARCHAR(120) NULL,
    plano_transicao_hc TEXT NULL,
    pendencia_familia_hc TEXT NULL,
    pendencia_hospital_hc TEXT NULL,
    pendencia_operadora_hc TEXT NULL,
    equipamentos_hc TEXT NULL,
    custo_hospital_dia_hc DECIMAL(12,2) NULL,
    custo_home_care_dia_hc DECIMAL(12,2) NULL,
    potencial_economia_hc DECIMAL(12,2) NULL,
    observacoes_hc TEXT NULL,
    nead_grupo1_cuidador_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo1_ambiente_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo1_locomocao_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo2_vm_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo2_aspiracao_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo2_medicacao_ev_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo2_dieta_parenteral_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo2_lesao_complexa_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_grupo3_katz_hc TINYINT NOT NULL DEFAULT 0,
    nead_grupo3_enteral_hc TINYINT NOT NULL DEFAULT 0,
    nead_grupo3_oxigenio_hc TINYINT NOT NULL DEFAULT 0,
    nead_grupo3_traqueostomia_hc TINYINT NOT NULL DEFAULT 0,
    nead_grupo3_dialise_hc TINYINT NOT NULL DEFAULT 0,
    nead_elegivel_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_indicacao_imediata_hc CHAR(1) NOT NULL DEFAULT 'n',
    nead_pontuacao_hc INT NOT NULL DEFAULT 0,
    nead_classificacao_hc VARCHAR(80) NULL,
    updated_at_hc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_home_care),
    KEY idx_hc_internacao (fk_internacao_hc),
    KEY idx_hc_status (status_hc),
    KEY idx_hc_data (data_atualizacao_hc),
    KEY idx_hc_implantacao (previsao_implantacao_hc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
